server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bug_check
    username: root
    password: woxihuanni1314
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    port: 3306
#    password:
#    database: ${bugCheck.redis.database}
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  devtools:
    restart:
      enabled: false
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.bug_check_background.pojo.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true
redis:
  # 地址
  host: 127.0.0.1
  # 端口，默认为6379
  port: 6379
  # 密码
  password: zhian
  # 连接超时时间
  timeout: 10s
  lettuce:
    pool:
      # 连接池中的最小空闲连接
      min-idle: 0
      # 连接池中的最大空闲连接
      max-idle: 100
      # 连接池的最大数据库连接数
      max-active: 500
      # #连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1m

sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: token
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: -1
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  #允许登录设置参数
  dynamicActiveTimeout: true
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: false
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: simple-uuid
  # 是否输出操作日志
  is-log: true
  # 是否尝试从 cookie 里读取 Token，此值为 false 后，StpUtil.login(id) 登录时也不会再往前端注入Cookie
  isReadCookie: false
  # 是否尝试从 header 里读取 Token
  is-read-head: true
  # 是否开启自动续签
  auto-renew: true
  alone-redis:
    # Redis数据库索引（默认为0）
    database: 0
    # Redis服务器地址
    #    host: 127.0.0.1
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: Marine.123
    # 连接超时时间
    timeout: 10s
  # jwt秘钥
  jwt-secret-key: zhian
