server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bug_check
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: ${bugCheck.redis.host}
    port: ${bugCheck.redis.port}
    password: ${bugCheck.redis.password}
    database: ${bugCheck.redis.database}
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  devtools:
    restart:
      enabled: false
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.bug_check_background.pojo.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true